# Generated by Django 5.0.3 on 2024-03-31 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(blank=True, default='', max_length=100)),
                ('instructor', models.CharField(blank=True, default='', max_length=100)),
                ('duration', models.IntegerField(null=True)),
                ('description', models.TextField(null=True)),
                ('price', models.FloatField(null=True)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
